# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
