# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prod',
            new_name='Product',
        ),
    ]
