# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_auto_20180621_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
