# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
